apiVersion: v1
items:
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2017-11-21T23:45:52Z
    name: admin
    namespace: mem-tfrs-prod
    resourceVersion: "355762951"
    selfLink: /oapi/v1/namespaces/mem-tfrs-prod/rolebindings/admin
    uid: 1bcf7359-cf16-11e7-8fdb-0050568348cc
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: sheaphillips
  - kind: User
    name: rajpersram
  - kind: User
    name: kuanfandevops
  - kind: User
    name: cvarjao
  userNames:
  - sheaphillips
  - rajpersram
  - kuanfandevops
  - cvarjao
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2017-11-21T23:45:52Z
    name: edit
    namespace: mem-tfrs-prod
    resourceVersion: "340071664"
    selfLink: /oapi/v1/namespaces/mem-tfrs-prod/rolebindings/edit
    uid: 1bcfa03c-cf16-11e7-8fdb-0050568348cc
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: default
    namespace: mem-tfrs-tools
  - kind: User
    name: dmarley
  - kind: User
    name: swcurran
  - kind: User
    name: GeorgeWalker
  - kind: User
    name: dainetrinidad
  - kind: User
    name: rstens
  - kind: ServiceAccount
    name: jenkins
    namespace: mem-tfrs-tools
  - kind: User
    name: DerekRoberts
  userNames:
  - system:serviceaccount:mem-tfrs-tools:default
  - dmarley
  - swcurran
  - GeorgeWalker
  - dainetrinidad
  - rstens
  - system:serviceaccount:mem-tfrs-tools:jenkins
  - DerekRoberts
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2017-11-21T23:45:52Z
    name: system:deployers
    namespace: mem-tfrs-prod
    resourceVersion: "355762955"
    selfLink: /oapi/v1/namespaces/mem-tfrs-prod/rolebindings/system%3Adeployers
    uid: 1bd5e87e-cf16-11e7-8fdb-0050568348cc
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: mem-tfrs-prod
  userNames:
  - system:serviceaccount:mem-tfrs-prod:deployer
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2017-11-21T23:45:52Z
    name: system:image-builders
    namespace: mem-tfrs-prod
    resourceVersion: "355762958"
    selfLink: /oapi/v1/namespaces/mem-tfrs-prod/rolebindings/system%3Aimage-builders
    uid: 1bd668d5-cf16-11e7-8fdb-0050568348cc
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
    namespace: mem-tfrs-prod
  userNames:
  - system:serviceaccount:mem-tfrs-prod:builder
- apiVersion: v1
  groupNames:
  - system:serviceaccounts:mem-tfrs-prod
  kind: RoleBinding
  metadata:
    creationTimestamp: 2017-11-21T23:45:52Z
    name: system:image-pullers
    namespace: mem-tfrs-prod
    resourceVersion: "355762960"
    selfLink: /oapi/v1/namespaces/mem-tfrs-prod/rolebindings/system%3Aimage-pullers
    uid: 1bd656d2-cf16-11e7-8fdb-0050568348cc
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:mem-tfrs-prod
  userNames: null
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2017-11-21T23:45:52Z
    name: view
    namespace: mem-tfrs-prod
    resourceVersion: "355762964"
    selfLink: /oapi/v1/namespaces/mem-tfrs-prod/rolebindings/view
    uid: 1bcb8819-cf16-11e7-8fdb-0050568348cc
  roleRef:
    name: view
  subjects:
  - kind: User
    name: matthewhall78
  - kind: User
    name: swcurran
  userNames:
  - matthewhall78
  - swcurran
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
