apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-class: gluster-file
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
    creationTimestamp: 2018-05-15T17:56:38Z
    name: jenkins-backup
    namespace: mem-tfrs-tools
    resourceVersion: "466884331"
    selfLink: /api/v1/namespaces/mem-tfrs-tools/persistentvolumeclaims/jenkins-backup
    uid: 509e48f6-5869-11e8-ae7a-005056832285
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeName: pvc-509e48f6-5869-11e8-ae7a-005056832285
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-class: gluster-file
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
    creationTimestamp: 2018-01-19T21:36:42Z
    name: jenkins-cns2
    namespace: mem-tfrs-tools
    resourceVersion: "466226763"
    selfLink: /api/v1/namespaces/mem-tfrs-tools/persistentvolumeclaims/jenkins-cns2
    uid: d753561f-fd60-11e7-b70e-005056832285
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeName: pvc-d753561f-fd60-11e7-b70e-005056832285
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-class: gluster-file
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
    creationTimestamp: 2018-02-15T22:54:03Z
    name: postgresql-sonarqube-data
    namespace: mem-tfrs-tools
    resourceVersion: "466226765"
    selfLink: /api/v1/namespaces/mem-tfrs-tools/persistentvolumeclaims/postgresql-sonarqube-data
    uid: 1e329a9c-12a3-11e8-b39a-0050568348cc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: pvc-1e329a9c-12a3-11e8-b39a-0050568348cc
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-class: gluster-file
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
    creationTimestamp: 2018-02-15T22:54:03Z
    name: sonarqube-data
    namespace: mem-tfrs-tools
    resourceVersion: "466226769"
    selfLink: /api/v1/namespaces/mem-tfrs-tools/persistentvolumeclaims/sonarqube-data
    uid: 1e33dd23-12a3-11e8-b39a-0050568348cc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: pvc-1e33dd23-12a3-11e8-b39a-0050568348cc
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
