apiVersion: v1
items:
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2017-11-21T23:45:47Z
    name: admin
    namespace: mem-tfrs-tools
    resourceVersion: "466379526"
    selfLink: /oapi/v1/namespaces/mem-tfrs-tools/rolebindings/admin
    uid: 1901bf80-cf16-11e7-8fdb-0050568348cc
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: sheaphillips
  - kind: User
    name: rajpersram
  - kind: User
    name: kuanfandevops
  - kind: User
    name: cvarjao
  - kind: User
    name: amichard
  userNames:
  - sheaphillips
  - rajpersram
  - kuanfandevops
  - cvarjao
  - amichard
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2017-11-21T23:45:47Z
    labels:
      app: jenkins-pipeline
      template: jenkins-persistent-template
    name: jenkins_edit
    namespace: mem-tfrs-tools
    resourceVersion: "466379529"
    selfLink: /oapi/v1/namespaces/mem-tfrs-tools/rolebindings/jenkins_edit
    uid: 18ecbc38-cf16-11e7-8fdb-0050568348cc
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: mem-tfrs-tools
  - kind: User
    name: matthewhall78
  - kind: User
    name: rstens
  - kind: User
    name: DerekRoberts
  userNames:
  - system:serviceaccount:mem-tfrs-tools:jenkins
  - matthewhall78
  - rstens
  - DerekRoberts
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2017-11-21T23:45:47Z
    name: system:deployers
    namespace: mem-tfrs-tools
    resourceVersion: "466379530"
    selfLink: /oapi/v1/namespaces/mem-tfrs-tools/rolebindings/system%3Adeployers
    uid: 18ecccbc-cf16-11e7-8fdb-0050568348cc
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: mem-tfrs-tools
  userNames:
  - system:serviceaccount:mem-tfrs-tools:deployer
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2017-11-21T23:45:47Z
    name: system:image-builders
    namespace: mem-tfrs-tools
    resourceVersion: "466379534"
    selfLink: /oapi/v1/namespaces/mem-tfrs-tools/rolebindings/system%3Aimage-builders
    uid: 18ec6459-cf16-11e7-8fdb-0050568348cc
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
    namespace: mem-tfrs-tools
  userNames:
  - system:serviceaccount:mem-tfrs-tools:builder
- apiVersion: v1
  groupNames:
  - system:serviceaccounts:mem-tfrs-tools
  kind: RoleBinding
  metadata:
    creationTimestamp: 2017-11-21T23:45:47Z
    name: system:image-pullers
    namespace: mem-tfrs-tools
    resourceVersion: "466379537"
    selfLink: /oapi/v1/namespaces/mem-tfrs-tools/rolebindings/system%3Aimage-pullers
    uid: 18f56713-cf16-11e7-8fdb-0050568348cc
  roleRef:
    name: system:image-puller
  subjects:
  - kind: ServiceAccount
    name: default
    namespace: mem-tfrs-dev
  - kind: ServiceAccount
    name: default
    namespace: mem-tfrs-test
  - kind: ServiceAccount
    name: default
    namespace: mem-tfrs-prod
  - kind: ServiceAccount
    name: jenkins
    namespace: default
  - kind: ServiceAccount
    name: jenkins-pipeline-svc
    namespace: default
  - kind: ServiceAccount
    name: deployer
    namespace: mem-tfrs-dev
  - kind: SystemGroup
    name: system:serviceaccounts:mem-tfrs-tools
  userNames:
  - system:serviceaccount:mem-tfrs-dev:default
  - system:serviceaccount:mem-tfrs-test:default
  - system:serviceaccount:mem-tfrs-prod:default
  - system:serviceaccount:default:jenkins
  - system:serviceaccount:default:jenkins-pipeline-svc
  - system:serviceaccount:mem-tfrs-dev:deployer
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2017-11-21T23:45:47Z
    name: view
    namespace: mem-tfrs-tools
    resourceVersion: "466379541"
    selfLink: /oapi/v1/namespaces/mem-tfrs-tools/rolebindings/view
    uid: 1900e8a9-cf16-11e7-8fdb-0050568348cc
  roleRef:
    name: view
  subjects:
  - kind: User
    name: swcurran
  - kind: ServiceAccount
    name: jenkins
    namespace: default
  userNames:
  - swcurran
  - system:serviceaccount:default:jenkins
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
