apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-class: gluster-file
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
    creationTimestamp: 2018-02-28T23:08:15Z
    name: postgresql-backup-cns
    namespace: mem-tfrs-dev
    resourceVersion: "356641030"
    selfLink: /api/v1/namespaces/mem-tfrs-dev/persistentvolumeclaims/postgresql-backup-cns
    uid: 41929239-1cdc-11e8-8a7d-005056832285
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    volumeName: pvc-41929239-1cdc-11e8-8a7d-005056832285
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-class: gluster-file
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
    creationTimestamp: 2018-02-16T22:36:16Z
    name: postgresql-bypass-cns
    namespace: mem-tfrs-dev
    resourceVersion: "343409739"
    selfLink: /api/v1/namespaces/mem-tfrs-dev/persistentvolumeclaims/postgresql-bypass-cns
    uid: cccc95a2-1369-11e8-844f-005056832285
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: pvc-cccc95a2-1369-11e8-844f-005056832285
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-class: gluster-file
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
    creationTimestamp: 2018-01-19T23:21:37Z
    name: postgresql-cns
    namespace: mem-tfrs-dev
    resourceVersion: "320002505"
    selfLink: /api/v1/namespaces/mem-tfrs-dev/persistentvolumeclaims/postgresql-cns
    uid: 7f1938e3-fd6f-11e7-b70e-005056832285
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: pvc-7f1938e3-fd6f-11e7-b70e-005056832285
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-class: gluster-file
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
    creationTimestamp: 2018-03-01T23:48:17Z
    name: postgresql-standby-cns
    namespace: mem-tfrs-dev
    resourceVersion: "357893436"
    selfLink: /api/v1/namespaces/mem-tfrs-dev/persistentvolumeclaims/postgresql-standby-cns
    uid: 03f2bc9c-1dab-11e8-8a7d-005056832285
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    volumeName: pvc-03f2bc9c-1dab-11e8-8a7d-005056832285
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 5Gi
    phase: Bound
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
